setup azure managed prometheus for svc/mgmt clusters
Azure/ARO-HCP pull request #439
Opened 2024-08-02 16:54 UTC by tony-schndr

### What this PR does
- adds deployment templates to deploy Azure Monitor Workspace with Grafana including a new make target `metrics-infra`
- adds deployment template to deploy data collection endpoint, data collection rule, default prometheus, and data collection rule association per aks cluster including a new make target called `aks-metrics`
- updates dev infra CD pipeline to deploy metrics infra and aks metrics infrastructure
- updates dev-infrastructure/docs/ for deploying the metrics stack

Jira: https://issues.redhat.com/browse/ARO-9335
Link to demo recording: 

### Special notes for your reviewer

2024-08-02 17:37 UTC, mjlshen requested changes

2024-08-02 17:37 UTC, mjlshen commented on dev-infrastructure/templates/Alerts.bicep
I think by existing convention in the repo, we would put `Alerts.bicep` into modules since it's not something we will verison directly

2024-08-02 17:37 UTC, mjlshen commented on dev-infrastructure/templates/Metrics.bicep
Similar, I think by existing convention in the repo, we would put the contents of `Metrics.bicep` into [region.bicep](https://github.com/Azure/ARO-HCP/blob/main/dev-infrastructure/templates/region.bicep). The idea is that we can version our "region.bicep" and get one versioned entity for everything in our regional resource group

2024-08-02 17:37 UTC, mjlshen commented on dev-infrastructure/templates/aks-azure-monitor-metrics.bicep
Can this be pulled into [aks-cluster-base.bicep](https://github.com/Azure/ARO-HCP/blob/main/dev-infrastructure/modules/aks-cluster-base.bicep) as well, either as a separate module or literally in there?

2024-08-02 17:37 UTC, mjlshen commented on .github/workflows/aro-hcp-dev-env-cd.yml
> +                  clusterLocation=${REGION}
The result of addressing my other feedback would be that we maintain high level steps for:

* Configure `global` resource group (currently only ACR in dev, global DNS resources handled separately)
* Configure `regional` resource group
* Configure `service-cluster` resource group
* Configure `management-cluster` resource group

We may add more categories in the future, but I think this Managed Prometheus/Grafana work does fit nicely into our existing buckets

2024-08-07 06:00 UTC, geoberle commented on dev-infrastructure/modules/metrics/aks-azure-monitor-metrics.bicep
> +var dceName = 'MSProm-${azureMonitorWorkspaceLocation}-${clusterName}'
the MSFT naming scheme names all AKS clusters the same. the resource group names will be unique though, even across subscriptions.

2024-08-07 14:40 UTC, tony-schndr commented on dev-infrastructure/modules/metrics/aks-azure-monitor-metrics.bicep
> +var dceName = 'MSProm-${azureMonitorWorkspaceLocation}-${clusterName}'
as discussed, these data collection endpoints and data collection rules are deployed within the svc-cluster/mgmt-cluster resource groups and are 1:1 with the aks cluster, therefore there would be no naming collisions.

2024-08-07 17:43 UTC, mjlshen approved these changes

2024-08-07 17:43 UTC, merged